### ISSUE TITLE
Hii, How to use the actor3d.setRoation?

### ISSUE THREAD

**Issue by tianqiujie** [pyros2097/Scene3d#6]
instance.transform.rotate(new Vector3(0, 1, 0), perAngle * i);

and in Scene3D, i just found action3d.setRoation(x, y, z) ????

please help me. I am make a game use your Scene3D, thank you

**Comment by pyros2097** [comment]
Actually Scene3d uses an outdated libgdx and I haven't yet fixed the bugs like this https://github.com/pyros2097/Scene3d/blob/master/src/scene3d/demo/Scene3dDemo.java#L269 .. And I think if your are using actions then you have to create a new one like this https://github.com/pyros2097/Scene3d/blob/master/src/scene3d/actions/Actions3d.java#L119 ... Just setting the value might now make a difference. If you are talking about an Actor I think I don't remember If that was possible.

**Comment by tianqiujie** [comment]
Hi, sir. I used your scene3d, It very useful. Thank you very much.
